/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.desarrollo;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;

/**
 *
 * @author usuario
 */
public class ModificarDatosUsuario extends javax.swing.JFrame {

    ConexionBD enlace = new ConexionBD();
    Connection conect = enlace.conectar();
    /**
     * Creates new form registroUsuario
     */
    public ModificarDatosUsuario() {
        initComponents();
        grupoBotones();
    }

    private void grupoBotones(){
        ButtonGroup grupo = new ButtonGroup();
        grupo.add(radiobuttonUsuario);
        grupo.add(radiobuttonPass);
        grupo.add(radiobuttonNombre);
        grupo.add(radiobuttonTelefono);
        grupo.add(radiobuttonDireccion);
        grupo.add(radiobuttonCiudad);
        grupo.add(radiobuttonCargo);
        grupo.add(radiobuttonSede);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    //Se obitnenen los datos de la BD y estan contenidos en un arreglo
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        labelCiudad = new javax.swing.JLabel();
        labelSede = new javax.swing.JLabel();
        labelSeleccion = new javax.swing.JLabel();
        radiobuttonUsuario = new javax.swing.JRadioButton();
        radiobuttonPass = new javax.swing.JRadioButton();
        radiobuttonNombre = new javax.swing.JRadioButton();
        radiobuttonTelefono = new javax.swing.JRadioButton();
        radiobuttonDireccion = new javax.swing.JRadioButton();
        radiobuttonCiudad = new javax.swing.JRadioButton();
        radiobuttonCargo = new javax.swing.JRadioButton();
        radiobuttonSede = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        titulo.setText("MODIFICAR DATOS DE USUARIO");

        labelUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUser.setText("Usuario");

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombre.setText("Nombre");

        labelCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCargo.setText("Cargo");

        labelDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDireccion.setText("Dirección");

        labelTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTelefono.setText("Telefono");

        labelPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPass.setText("Contraseña");

        botonRegistrar.setText("Seleccionar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        labelCiudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCiudad.setText("Ciudad");

        labelSede.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSede.setText("Sede");

        labelSeleccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSeleccion.setText("Seleccione los elementos que desea actualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSeleccion)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(botonRegresar)
                                .addGap(52, 52, 52)
                                .addComponent(botonRegistrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radiobuttonUsuario)
                            .addComponent(radiobuttonPass)
                            .addComponent(radiobuttonNombre)
                            .addComponent(radiobuttonTelefono)
                            .addComponent(radiobuttonDireccion)
                            .addComponent(radiobuttonCiudad)
                            .addComponent(radiobuttonCargo)
                            .addComponent(radiobuttonSede))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelUser)
                                .addComponent(labelPass)
                                .addComponent(labelNombre)
                                .addComponent(labelTelefono)
                                .addComponent(labelCargo)
                                .addComponent(labelCiudad)
                                .addComponent(labelSede))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDireccion)
                                .addGap(18, 18, 18)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(labelSeleccion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addComponent(labelUser)
                                                                            .addComponent(radiobuttonUsuario))
                                                                        .addGap(6, 6, 6)
                                                                        .addComponent(labelPass))
                                                                    .addComponent(radiobuttonPass))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(labelNombre))
                                                            .addComponent(radiobuttonNombre))
                                                        .addGap(6, 6, 6)
                                                        .addComponent(labelTelefono))
                                                    .addComponent(radiobuttonTelefono))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelDireccion))
                                            .addComponent(radiobuttonDireccion))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelCiudad))
                                    .addComponent(radiobuttonCiudad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCargo))
                            .addComponent(radiobuttonCargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSede))
                    .addComponent(radiobuttonSede))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrar)
                    .addComponent(botonRegresar))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:            
        if(radiobuttonUsuario.isSelected()){
            ModificarUsuario regresar=new ModificarUsuario();
            regresar.setVisible(true);
            this.setVisible(false);
            try {
                enlace.cerrar();
            } catch (SQLException ex) {
                Logger.getLogger(ModificarDatosUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        MenuUsuario regresar=new MenuUsuario();
        regresar.setVisible(true);
        this.setVisible(false);
        try {
            enlace.cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(ModificarDatosUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ModificarDatosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelSede;
    private javax.swing.JLabel labelSeleccion;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelUser;
    private javax.swing.JRadioButton radiobuttonCargo;
    private javax.swing.JRadioButton radiobuttonCiudad;
    private javax.swing.JRadioButton radiobuttonDireccion;
    private javax.swing.JRadioButton radiobuttonNombre;
    private javax.swing.JRadioButton radiobuttonPass;
    private javax.swing.JRadioButton radiobuttonSede;
    private javax.swing.JRadioButton radiobuttonTelefono;
    private javax.swing.JRadioButton radiobuttonUsuario;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
