/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.desarrollo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class ModificarContrasenia extends javax.swing.JFrame {

    /**
     * Creates new form ModificarUser
     */
    
    ConexionBD enlace = new ConexionBD();
    Connection conect = enlace.conectar();
    public ModificarContrasenia() {
        initComponents();
    }
    
    
    private void modificarContrasenia(){
        String []datos = new String[2];
        try{
            Statement leer = conect.createStatement();
            ResultSet resultado = leer.executeQuery("SELECT usuario_emp,contrasenia_emp FROM empleado");
                
            while(resultado.next()){
                datos[0]=resultado.getString(1);
                datos[1]=resultado.getString(2);
            }
            
            if(datos[0].equals(fieldUsuario.getText())
                    && datos[1].equals(fieldContraseniaAnterior.getText())){
                if(fieldContraseniaNueva.getText().equals(fieldContraseniaNueva2.getText())){
                    if(!fieldContraseniaAnterior.getText().equals(fieldContraseniaNueva.getText())){
                        PreparedStatement actualizar = conect.prepareStatement("UPDATE empleado SET contrasenia_emp=? WHERE usuario_emp=? AND contrasenia_emp=?");
                        actualizar.setString(1, fieldContraseniaNueva.getText());
                        actualizar.setString(2, fieldUsuario.getText());
                        actualizar.setString(3, fieldContraseniaAnterior.getText());
                        actualizar.executeUpdate();
                        enlace.cerrar();
                        JOptionPane.showMessageDialog(null, "Los datos se actualizaron correctamente");
                        regresarMenu();
                    }else{
                        JOptionPane.showMessageDialog(null, "La contraseña no puede ser igual a la anterior");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Las contraseñas deben coincidir");
                }
            }else{
                JOptionPane.showMessageDialog(null, "El usuario o contraseña no son correctos");
            }    
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No se completo el registro "+ e);
        }
    }
    
    private void regresarMenu(){
        ModificarDatosUsuario regresar=new ModificarDatosUsuario();
        regresar.setVisible(true);
        this.setVisible(false);
        try {
            enlace.cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(ModificarDatosUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        labelContraseniaAnterior = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        labelContraseniaNueva = new javax.swing.JLabel();
        fieldContraseniaNueva = new javax.swing.JPasswordField();
        labelContraseniaNueva2 = new javax.swing.JLabel();
        fieldContraseniaNueva2 = new javax.swing.JPasswordField();
        fieldContraseniaAnterior = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        titulo.setText("ACTUALIZAR CONTRASEÑA");

        labelUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUsuario.setText("Escriba el usuario");

        fieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsuarioActionPerformed(evt);
            }
        });

        labelContraseniaAnterior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelContraseniaAnterior.setText("Escriba la contraseña anterior");

        botonGuardar.setText("Guardar Cambios");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        labelContraseniaNueva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelContraseniaNueva.setText("Escriba la nueva contraseña");

        fieldContraseniaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldContraseniaNuevaActionPerformed(evt);
            }
        });

        labelContraseniaNueva2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelContraseniaNueva2.setText("Repita la nueva contraseña");

        fieldContraseniaNueva2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldContraseniaNueva2ActionPerformed(evt);
            }
        });

        fieldContraseniaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldContraseniaAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelUsuario)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botonRegresar)
                                .addComponent(labelContraseniaAnterior, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelContraseniaNueva, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelContraseniaNueva2, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldContraseniaNueva, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldContraseniaNueva2)
                            .addComponent(fieldContraseniaAnterior)))
                    .addComponent(titulo))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContraseniaAnterior)
                    .addComponent(fieldContraseniaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldContraseniaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContraseniaNueva))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContraseniaNueva2)
                    .addComponent(fieldContraseniaNueva2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonRegresar))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsuarioActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        modificarContrasenia();
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        regresarMenu();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void fieldContraseniaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldContraseniaNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldContraseniaNuevaActionPerformed

    private void fieldContraseniaNueva2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldContraseniaNueva2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldContraseniaNueva2ActionPerformed

    private void fieldContraseniaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldContraseniaAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldContraseniaAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarContrasenia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JPasswordField fieldContraseniaAnterior;
    private javax.swing.JPasswordField fieldContraseniaNueva;
    private javax.swing.JPasswordField fieldContraseniaNueva2;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel labelContraseniaAnterior;
    private javax.swing.JLabel labelContraseniaNueva;
    private javax.swing.JLabel labelContraseniaNueva2;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}